# pytest-cov enables "pytest --cov=application ."
name: Python Unit Testing & Code Coverage (pytest & pytest-cov)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov coverage
        pip install -r requirements.txt
        echo requirements installed
    - name: Run the tests
      run: |

        cd src
        python application.py &
        sleep 5
        python insert_data.py
        cd ../tests

        coverage run -m pytest test_application.py
        
        pytest --cov=application .
        pytest --cov=application --cov-report=html
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: tests/htmlcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}